[package]
name = "build_pluggables"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "build_pluggables"
path = "./build_pluggables.rs"

[dependencies]
anyhow = "1.0"
regex = "1.9"
serde_json = "1.0"

